// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABenAjjpCWsOtA0Ta0I1Uo9HNVozMFZ_k',
    appId: '1:911488665613:web:125fd9172d902ab9ae6d44',
    messagingSenderId: '911488665613',
    projectId: 'fruits-app-6b4a8',
    authDomain: 'fruits-app-6b4a8.firebaseapp.com',
    storageBucket: 'fruits-app-6b4a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNKndhJAuWyxif_MrO0cm8D6Uevh9G9fU',
    appId: '1:911488665613:android:0c76517f3f017ec4ae6d44',
    messagingSenderId: '911488665613',
    projectId: 'fruits-app-6b4a8',
    storageBucket: 'fruits-app-6b4a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCALHSQo5b3m8zfwZLBwrUahAiCXrPC6Z8',
    appId: '1:911488665613:ios:ac5a4c7f4b35c6eaae6d44',
    messagingSenderId: '911488665613',
    projectId: 'fruits-app-6b4a8',
    storageBucket: 'fruits-app-6b4a8.firebasestorage.app',
    androidClientId: '911488665613-stad5ck3ipj0b7q6p9c79hinaqvdulgm.apps.googleusercontent.com',
    iosClientId: '911488665613-5f2j9hssjvpvajkrn7knii7lam2p6cli.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCALHSQo5b3m8zfwZLBwrUahAiCXrPC6Z8',
    appId: '1:911488665613:ios:ac5a4c7f4b35c6eaae6d44',
    messagingSenderId: '911488665613',
    projectId: 'fruits-app-6b4a8',
    storageBucket: 'fruits-app-6b4a8.firebasestorage.app',
    androidClientId: '911488665613-stad5ck3ipj0b7q6p9c79hinaqvdulgm.apps.googleusercontent.com',
    iosClientId: '911488665613-5f2j9hssjvpvajkrn7knii7lam2p6cli.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABenAjjpCWsOtA0Ta0I1Uo9HNVozMFZ_k',
    appId: '1:911488665613:web:e08d36ab659d54d5ae6d44',
    messagingSenderId: '911488665613',
    projectId: 'fruits-app-6b4a8',
    authDomain: 'fruits-app-6b4a8.firebaseapp.com',
    storageBucket: 'fruits-app-6b4a8.firebasestorage.app',
  );
}
